"use client";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend } from "recharts";
import { MonthlyData } from "@/types/valuation";
const RC={Buy:"#10B981",Sell:"#EF4444",Investment:"#F59E0B"};
const TC=["#0F172A","#10B981"];
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const CT=({active,payload,label}:any)=>{ if(!active||!payload?.length)return null; return(<div className="bg-white border border-[#E5E7EB] rounded-lg shadow-lg p-3 text-xs"><p className="font-semibold text-[#0F172A] mb-2">{label}</p>{payload.map((p:any)=><div key={p.name} className="flex items-center gap-2 mb-1"><div className="w-2 h-2 rounded-full" style={{background:p.color}}/><span className="text-[#6B7280]">{p.name}:</span><span className="font-semibold text-[#0F172A]">{p.value}</span></div>)}</div>);};
export function MonthlyTrendChart({monthly}:{monthly:MonthlyData[]}){
  const data=monthly.slice(-12).map(m=>({name:m.month.slice(0,3),count:m.count}));
  return(<div className="bg-white rounded-xl border border-[#E5E7EB] p-6"><h3 className="text-sm font-semibold text-[#0F172A] mb-1">Monthly Trend</h3><p className="text-xs text-[#9CA3AF] mb-5">Assignments per month</p><ResponsiveContainer width="100%" height={200}><BarChart data={data} barSize={28}><CartesianGrid strokeDasharray="3 3" stroke="#F3F4F6" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11,fill:"#9CA3AF"}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11,fill:"#9CA3AF"}} axisLine={false} tickLine={false} width={28}/><Tooltip content={<CT/>}/><Bar dataKey="count" fill="#0F172A" radius={[4,4,0,0]} name="Valuations"/></BarChart></ResponsiveContainer></div>);
}
export function RecommendationChart({buy,sell,investment}:{buy:number;sell:number;investment:number}){
  const data=[{name:"Buy",value:buy},{name:"Sell",value:sell},{name:"Investment",value:investment}].filter(d=>d.value>0);
  const total=buy+sell+investment;
  return(<div className="bg-white rounded-xl border border-[#E5E7EB] p-6"><h3 className="text-sm font-semibold text-[#0F172A] mb-1">Recommendations</h3><p className="text-xs text-[#9CA3AF] mb-4">Buy/Sell/Investment split</p><div className="flex items-center gap-4"><ResponsiveContainer width={160} height={160}><PieChart><Pie data={data} cx="50%" cy="50%" innerRadius={48} outerRadius={72} dataKey="value" strokeWidth={0}>{data.map(e=><Cell key={e.name} fill={RC[e.name as keyof typeof RC]}/>)}</Pie></PieChart></ResponsiveContainer><div className="flex-1 space-y-3">{data.map(d=><div key={d.name}><div className="flex justify-between items-center mb-1"><div className="flex items-center gap-2"><div className="w-2.5 h-2.5 rounded-full" style={{background:RC[d.name as keyof typeof RC]}}/><span className="text-xs text-[#6B7280]">{d.name}</span></div><span className="text-xs font-semibold text-[#0F172A]">{total>0?Math.round(d.value/total*100):0}%</span></div><div className="h-1.5 bg-[#F3F4F6] rounded-full overflow-hidden"><div className="h-full rounded-full" style={{width:`${total>0?d.value/total*100:0}%`,background:RC[d.name as keyof typeof RC]}}/></div></div>)}</div></div></div>);
}
export function PropertySplitChart({residential,commercial}:{residential:number;commercial:number}){
  const data=[{name:"Residential",value:residential},{name:"Commercial",value:commercial}];
  return(<div className="bg-white rounded-xl border border-[#E5E7EB] p-6"><h3 className="text-sm font-semibold text-[#0F172A] mb-1">Property Types</h3><p className="text-xs text-[#9CA3AF] mb-4">Residential vs Commercial</p><ResponsiveContainer width="100%" height={160}><PieChart><Pie data={data} cx="50%" cy="50%" outerRadius={65} dataKey="value" strokeWidth={0} label={({name,percent})=>`${name} ${Math.round((percent??0)*100)}%`} labelLine={false}>{data.map((_,i)=><Cell key={i} fill={TC[i]}/>)}</Pie><Legend iconType="circle" iconSize={8} formatter={(v)=><span className="text-xs text-[#6B7280]">{v}</span>}/><Tooltip/></PieChart></ResponsiveContainer></div>);
}
