"use client";
import { Valuation } from "@/types/valuation";
import { formatCrore } from "@/lib/analytics";
interface Props { valuations: Valuation[]; limit?: number; }
const rb:Record<string,string>={Buy:"bg-emerald-50 text-emerald-700 border border-emerald-200",Sell:"bg-red-50 text-red-700 border border-red-200",Investment:"bg-amber-50 text-amber-700 border border-amber-200"};
const tb:Record<string,string>={Residential:"bg-blue-50 text-blue-700 border border-blue-200",Commercial:"bg-purple-50 text-purple-700 border border-purple-200"};
export default function DataTable({valuations,limit=10}:Props){
  const rows=valuations.slice(0,limit);
  return(<div className="bg-white rounded-xl border border-[#E5E7EB] overflow-hidden"><div className="px-6 py-4 border-b border-[#F3F4F6]"><h3 className="text-sm font-semibold text-[#0F172A]">Recent Valuations</h3></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-[#F3F4F6]">{["Property Name","City","Type","Recommendation","Value"].map(h=><th key={h} className="text-left px-6 py-3 text-xs font-semibold text-[#9CA3AF] uppercase tracking-wider whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{rows.map((v,i)=><tr key={i} className="border-b border-[#F9FAFB] hover:bg-[#FAFAFA]"><td className="px-6 py-3.5"><div className="font-medium text-[#0F172A]">{v.property_name}</div><div className="text-xs text-[#9CA3AF]">{v.developer_name}</div></td><td className="px-6 py-3.5 text-[#374151] whitespace-nowrap">{v.city}</td><td className="px-6 py-3.5"><span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${tb[v.property_type]||""}`}>{v.property_type}</span></td><td className="px-6 py-3.5"><span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold ${rb[v.recommendation_type]||""}`}>{v.recommendation_type}</span></td><td className="px-6 py-3.5 font-semibold text-[#0F172A] whitespace-nowrap">{formatCrore(v.mb_research_value)}</td></tr>)}{rows.length===0&&<tr><td colSpan={5} className="px-6 py-8 text-center text-sm text-[#9CA3AF]">No valuations found.</td></tr>}</tbody></table></div></div>);
}
